#╔═════════════════════════════════════════════════════╗
#║                     Bounty's Staff                  ║
#║                                                     ║
#║                  Made by BountyGames                ║
#╚═════════════════════════════════════════════════════╝

prefix : "&7[&bBounty's Staff&7] "

lang: en
langs:
  - en
  - fr
  - de
  - es
  - it
  - jp

